name: celar_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  hand_signature: ^3.0.1
  permission_handler: ^11.3.1
  http: ^0.13.3
  shared_preferences: ^2.0.8
  image_picker: ^0.8.7+4
  webview_flutter: ^4.0.7
  flutter_widget_from_html: ^0.15.3
  chewie: ^1.4.2
  video_player: ^2.5.0
  url_launcher: ^6.1.10
  flutter_pdfview: ^1.0.0
  path_provider: ^2.0.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/